relax:
  image: relax/relax
  environment:
    relax_demo: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: relax=true
  links:
    - mongo:mongo
  volumes:
    - /docker/relax/media:/app/public/media
mongo:
  image: mongo
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: relax=true
  volumes:
    - /docker/mongo/data:/data/db
